config/routes.rb
SampleApp::Application.routes.draw do

  root :to => 'static_pages#home' 
  get 'static_pages/help', :as => 'help'
  get 'static_pages/about', :as => 'about'
  get 'static_pages/contact', :as => 'contact'
  get 'static_pages/staples', :as => 'staples'
  get 'static_pages/canvas', :as => 'canvas'
  get 'signup'  => 'users#new', :as => 'signup'

  get 'products/:id' => 'products#show'
  get 'products'    => 'products#all'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name,  presence: true, length: { maximum: 50 }
  validates :url, presence: true, length: { maximum: 255 }
  validates :price, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  has_secure_password
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.find_by_id(params[:id]) 
    unless @product.nil?
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @product }
      end
    end
  end

  def all
    @products = Product.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    debugger
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def staples
  end

  def canvas
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
            <li><%= link_to "Home"    , root_path %></li>
            <li><%= link_to "Products", products_path %></li>
            <li><%= link_to "Help"    , help_path %></li>
            <li><%= link_to "Log in"  , login_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/products/all.html.erb
<% @products.each do |product| %>
  <p>
    <b>Product:</b>
    <%= product.name %>
  </p>
  <%= link_to(image_tag("#{product.url}", :alt => "#{product.name}", :width => 100, :height => 100, :title => "#{product.description}"), "/products/#{product.id}") %>
  <div class="yotpo bottomLine"
    data-appkey="hxIWuX8DE7NP4nVBytcGAhFPgZexr59o3dgNVYC1"
    data-domain="127.0.0.1"
    data-product-models="information"
    data-product-id="SKU<%= product.id %>"
    data-name="<%= product.name %>"
    data-url="/products/<%= product.id %>"
    data-image-url="<%= product.url %>"
    data-description="<%= product.description %>"
    data-bread-crumbs="mammals">
  </div>
  <br/>
<% end %>

app/views/products/show.html.erb
<% unless @product.nil?%>
  <p>
    <b>Product:</b>
    <%= @product.name %>
  </p>
  <%= image_tag("#{@product.url}", :alt => "#{@product.name}", :width => 300, :height => 300, :title => "#{@product.description}") %>
  <div class="yotpo yotpo-main-widget"
    data-product-id="SKU<%= @product.id %>"
    data-name="<%= @product.name %>"
    data-url="/products/<%= @product.id %>"
    data-image-url="<%= @product.url %>"
    data-description="<%= @product.description %>">
  </div>
  <div class="yotpo-user-reference"  data-user-reference="345"></div>
  <div class='yotpo QABottomLine'
    data-appkey='vEiVh2yHSPM9TzTjPeRkLRJ4pRGGIgwS4sxgfvSF'
    data-product-id="SKU<%= @product.id %>">
  </div>
<% else %>
  <p>
    <b>Please Add Products</b>
  </p>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/canvas.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Smiley Face</title>
        <%= javascript_include_tag "drawing.js" %>
    </head>
    <body>
        <canvas id="a" width="200" height="200">
            This text is displayed if your browser does not support HTML5 Canvas.
        </canvas>
    </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help
  section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
  Tutorial</em> book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>

app/views/static_pages/staples.html.erb
<div  class="yotpo yotpo-main-widget" 
      data-product-id="135848" 
      data-name="LG 32LK330 32" 
      data-url="www.staples.com/product_353900" 
      data-image-url="http://www.staples-3p.com/s7/is/image/Staples/s0424806_sc7?$grid4$" 
      data-description="LG 32LK330 32">
</div>
<script type="text/javascript">
(function e(){var e=document.createElement("script");e.type="text/javascript",e.async=true,e.src="//staticw2.yotpo.com/8HInAM16rIurFVEWn4jXhNVsGbUZ2r8pmQ6WYd5z/widget.js";var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)})();
</script>

app/views/usernotifier/send_test_mail.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Hey, <%= @user.name %>!</h1>
  </body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>